### ISSUE TITLE
Task improvements

### ISSUE THREAD

**Issue by Nkiuru** [joonasmkauppinen/project-mirror#186]
- [x] Function to reset task,js if navigating away 
from task page --> **taskReset**
  - [x] Integrate this function in the Task
- [x] Sending answered task to server --> **taskSubmitData**
  - [x] Integrate this function in the Task
- [x] add get task description function --> **taskDescription**
  - [x] Integrate this function in the Task

**Comment by samuliv** [comment]
All functions added. Integration (implementation in frontend) checboxes also added and waiting for integration in Frontend/React.
