### ISSUE TITLE
Ellis "typing..." implementation HUMANIZATION for the Bot

### ISSUE THREAD

**Issue by samuliv** [joonasmkauppinen/project-mirror#213]
FEATURE:

Ellis not to directly answer to the questions ... but to have like "typing the text..." animation GIF for randomized 0-3000ms and then showing the answer ;D simulating the real - "conversation with a real human being" ;D

dolan.jpg

**Comment by samuliv** [comment]
NIKLAS, could you check the code implemenation and do the required fixes... It works fine until you pass messages until the response is got back from bot (should add responses in logical order, not in the middle of the messages - and should not crash :))

**Comment by Nkiuru** [comment]
sure will have a look a little later
